# Generated by Django 3.0.7 on 2020-06-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='PortfolioProject',
        ),
    ]
