# Generated by Django 3.0.7 on 2020-06-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogproject',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='blogproject',
            name='url',
        ),
        migrations.AddField(
            model_name='blogproject',
            name='date',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='blogproject',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='blogproject',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
