# Generated by Django 3.0.7 on 2020-06-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20200605_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogproject',
            name='date',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='blogproject',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blogproject',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
