# Generated by Django 3.0.7 on 2020-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20200605_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogproject',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
