# Generated by Django 3.0.7 on 2020-06-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20200605_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogproject',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogproject',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
